server:
    port: "${port:8090}"
--- 
datasource: 
  sampleapp: 
    defaultSchema: ~
    driverClassName: com.mysql.cj.jdbc.Driver
   
    hibernate: 
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      hbm2ddl.method: update
      show_sql: true
    maxPoolSize: 20
    password: password
    url: "jdbc:mysql://localhost:3306/docker_db"
    username: root
