--- 
datasource: 
  sampleapp: 
    defaultSchema: ~
    driverClassName: com.mysql.cj.jdbc.Driver
    hibernate: 
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
      hbm2ddl.method: update
      show_sql: true
    maxPoolSize: 20
    password: mypassword
    url: "jdbc:mysql://localhost:3306/community"
    username: myuser
